feat: saramin parse
waveofmymind/GoodJob pull request #7
Opened 2023-05-23 15:43 UTC by PARKPARKWOO

2023-05-23 23:22 UTC, waveofmymind requested changes
메서드 이름만 수정하면 바로 PR 올릴게요!
수고하셨습니다!

2023-05-23 23:22 UTC, waveofmymind commented on src/main/java/com/goodjob/domain/job/SaraminApiManager.java
> +    public void abc() throws JsonProcessingException {
메서드 이름은 바꾸는 것이 좋아보입니다!

2023-05-24 00:08 UTC, PARKPARKWOO commented on src/main/java/com/goodjob/domain/job/SaraminApiManager.java
> +    public void abc() throws JsonProcessingException {
아ㅋㅋㅋㅋ 맞네요 임시로 만들어둔다고 하고 깜빡했습니다

2023-05-24 00:17 UTC, waveofmymind approved these changes
확인했습니다! 수고하셨어요!

2023-05-24 00:17 UTC, merged